name: Dart Verify

on: pull_request

jobs:
  build:
    if: false
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart *.freezed.dart"
      dart_sdk: "stable"
      platform: "vm"
